[package]
name = "celox-example-my-frontend-napi"
version.workspace = true
publish = false
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
celox-frontend-sdk = { workspace = true }
celox-napi = { workspace = true }
napi = { version = "=3.12.1", features = ["napi8"] }
napi-derive = "=3.6.3"

[build-dependencies]
napi-build = "=2.4.1"

[lints]
workspace = true
