[package]
name = "celox-example-my-frontend-napi"
version.workspace = true
publish = false
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
celox-frontend-sdk = { workspace = true }
celox-napi = { workspace = true }
napi = { workspace = true, features = ["napi8"] }
napi-derive.workspace = true

[build-dependencies]
napi-build.workspace = true

[lints]
workspace = true
