[package]
name = "lydite-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"
[dependencies]
serde_json.workspace = true
serde.workspace = true
lydite-ir.workspace = true
parol_runtime = "5.0"
scnr2 = "=0.5.2"
[build-dependencies]
parol = "5.0"

[lints]
workspace = true
