[package]
name = "celox-backend-x86"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Celox x86-64 machine-code backend"
edition.workspace = true

[dependencies]
tracing = { workspace = true }
celox-analysis = { path = "../celox-analysis" }
celox-design = { path = "../celox-design" }
celox-sir = { path = "../celox-sir" }
celox-state-layout = { path = "../celox-state-layout" }
fxhash = { workspace = true }
libc = { workspace = true }
memmap2 = "0.9"
num-bigint = { workspace = true }
iced-x86 = { version = "1.21", default-features = false, features = ["std", "encoder", "block_encoder", "decoder", "nasm", "op_code_info", "code_asm"] }

[dev-dependencies]
celox-sir-opt = { path = "../celox-sir-opt" }

[lints]
workspace = true
