[package]
name                  = "celox-slt"
version.workspace     = true
authors.workspace     = true
repository.workspace  = true
license.workspace     = true
description           = "Source-independent symbolic logic tree core for Celox"
edition.workspace     = true

[dependencies]
celox-design = { path = "../celox-design" }
fxhash       = { workspace = true }
num-bigint   = { workspace = true }
serde        = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
