[package]
name                  = "celox-sir"
version.workspace     = true
publish               = ["crates-io"]
authors.workspace     = true
repository.workspace  = true
license.workspace     = true
description           = "Backend-independent Simulator IR for Celox"
edition.workspace     = true
rust-version.workspace = true

[dependencies]
celox-analysis = { workspace = true }
celox-design   = { workspace = true }
fxhash         = { workspace = true }
num-bigint     = { workspace = true }
num-traits     = { workspace = true }
serde          = { workspace = true }

[lints]
workspace = true
