[package]
name = "lydite-celox"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
lydite-ir.workspace = true
serde_json.workspace = true

[dev-dependencies]
lydite-solver.workspace = true

[[bin]]
name = "lydite-celox-lift"
path = "src/main.rs"

[lints]
workspace = true
