[package]
name = "hwverify-verify"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
hwverify-ir.workspace = true
hwverify-solver.workspace = true

[dev-dependencies]
hwverify-syntax.workspace = true

[lints]
workspace = true
