[package]
name = "celox-backend-arm64"
version.workspace = true
publish = ["crates-io"]
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Celox AArch64 machine-code backend"
edition.workspace = true
rust-version.workspace = true

[dependencies]
celox-backend-common = { workspace = true }
celox-backend-x86 = { workspace = true }
celox-state-layout = { workspace = true }
dynasmrt = "5.1.0"
fxhash = { workspace = true }

[target.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.dev-dependencies]
libc = { workspace = true }

[lints]
workspace = true
