#!/usr/bin/env python3
"""Summarize the retained reports; all counts are recomputed from case rows."""
import argparse
import csv
import json
from collections import Counter
from pathlib import Path

STATUSES = ("passed", "rejected", "unexpected_accept", "mismatch", "emission_error", "compile_error", "runtime_error", "unsupported", "ignored")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=Path(__file__).resolve().parents[1] / "verification")
    args = parser.parse_args()
    reports = []
    for tool in ("verilator", "icarus"):
        report = json.loads((args.directory / f"{tool}.json").read_text())
        rows = {row["name"]: row for row in report["cases"]}
        if len(rows) != len(report["cases"]):
            raise ValueError(f"duplicate cases in {tool}")
        counts = Counter(row["status"] for row in rows.values())
        if set(counts) - set(STATUSES) or any(report["counts"].get(s, 0) != counts[s] for s in STATUSES):
            raise ValueError(f"inconsistent counts in {tool}")
        reports.append((report, rows))
    verilator, icarus = (r[1] for r in reports)
    if verilator.keys() != icarus.keys():
        raise ValueError("reports cover different cases; rerun both without --filter")
    names = sorted(verilator)
    both = sum(verilator[n]["status"] == icarus[n]["status"] == "passed" for n in names)
    either = sum("passed" in (verilator[n]["status"], icarus[n]["status"]) for n in names)
    lines = ["# Verification results", "", "Generated by `python3 scripts/summarize.py` from the retained JSON reports.",
             "See [investigation notes](../VERIFICATION_REPORT.md) for limitations and unresolved expectations.", ""]
    for report, _ in reports:
        lines.append(f"- **{report['tool']}**: {report['version']}")
    lines += ["", "| Result | Verilator | Icarus |", "| --- | ---: | ---: |"]
    for status in STATUSES:
        lines.append(f"| `{status}` | {reports[0][0]['counts'].get(status, 0)} | {reports[1][0]['counts'].get(status, 0)} |")
    lines += [f"| Total | {len(names)} | {len(names)} |", "",
              f"{both} cases pass both simulators; {either} pass at least one. A pass in one tool does not resolve a disagreement with the other.", "",
              "## Assertion disagreements and execution errors", "", "| Case | Verilator | Icarus |", "| --- | --- | --- |"]
    for name in names:
        statuses = (verilator[name]["status"], icarus[name]["status"])
        if set(statuses) & {"mismatch", "runtime_error", "unexpected_accept"}:
            lines.append(f"| `{name}` | `{statuses[0]}` | `{statuses[1]}` |")
    lines += ["", "## Known tool discrepancies", "",
              "`ignored` cases were not executed and do not count as passes. Their assertions remain unchanged.",
              "Use `--include-ignored` to recheck them; forced runs report their actual outcome and can fail.", ""]
    limitations = {}
    for report, rows in reports:
        for name in names:
            row = rows[name]
            if issue := row.get("known_issue"):
                if "category" in issue:
                    group = limitations.setdefault(issue["id"], {"issue": issue, "verilator": 0, "icarus": 0})
                    group[report["tool"]] += 1
                    continue
                sources = [f"[upstream {i}]({url})" for i, url in enumerate(issue["upstream"], 1)]
                sources += [f"[evidence {i}](../{path})" for i, path in enumerate(issue.get("evidence", []), 1)]
                links = ", ".join(sources)
                lines += [f"- **{report['tool']}** `{name}` (`{row['status']}`, observed in {issue['observed_version']}): {issue['reason']} {links}. {issue['standard']}"]
    if limitations:
        lines += ["", "## Reviewed toolchain limitations", "",
                  "These exact case exclusions preserve the original diagnostics and expectations. They do not turn unlisted failures into skips.",
                  "See [the review](../LIMITATIONS.md) and [pre-exclusion Verilator](limitations/verilator.json) / [Icarus](limitations/icarus.json) observations.", "",
                  "| Group | Stage | Verilator | Icarus |", "| --- | --- | ---: | ---: |"]
        for name, group in sorted(limitations.items()):
            anchor = name.replace("_", "-")
            lines.append(f"| [{name}](../LIMITATIONS.md#{anchor}) | {group['issue']['phase']} | {group['verilator']} | {group['icarus']} |")
    lines += ["", "The [CSV matrix](matrix.csv) contains every case. Full diagnostics and first failing comparisons are retained in [verilator.json](verilator.json) and [icarus.json](icarus.json).", ""]
    (args.directory / "README.md").write_text("\n".join(lines))
    with (args.directory / "matrix.csv").open("w", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(["case", "category", "expectation", "verilator", "icarus"])
        for name in names:
            writer.writerow([name, verilator[name]["category"], verilator[name]["expectation"], verilator[name]["status"], icarus[name]["status"]])
    print(f"{len(names)} cases; {both} pass both; {either} pass at least one")


if __name__ == "__main__":
    main()
