// Every group is a script file in the language of `crate::script`.

pub(super) struct Group {
    /// The file name, for diagnostics.
    pub file: &'static str,
    pub text: &'static str,
}

macro_rules! script {
    ($name:literal) => {
        Group {
            file: concat!("src/cases/", $name, ".vtest"),
            text: include_str!(concat!($name, ".vtest")),
        }
    };
}

pub(super) const GROUPS: &[Group] = &[
    script!("concurrent_initial"),
    script!("hierarchical_assignment"),
    script!("advanced_interface"),
    script!("array_literal"),
    script!("basic"),
    script!("case_switch"),
    script!("comb_observer"),
    script!("compare_matrix"),
    script!("concat_operators"),
    script!("concatenation"),
    script!("context_width"),
    script!("counter"),
    script!("data_access"),
    script!("duplicate_varpath"),
    script!("enum_type"),
    script!("expression_semantics"),
    script!("false_loop"),
    script!("ff_event_snapshot"),
    script!("ff_narrow_arrays"),
    script!("fifo_issue5"),
    script!("flip_flop"),
    script!("for_loop_unroll"),
    script!("four_state"),
    script!("four_state_expression_semantics"),
    script!("function_arguments"),
    script!("generic_identity"),
    script!("hierarchy"),
    script!("interface"),
    script!("issue3_repro"),
    script!("linear_sorter_pull"),
    script!("loop_idiom"),
    script!("multi_clock"),
    script!("nba_cross_block"),
    script!("nba_cross_block_empty"),
    script!("nba_dynamic_array"),
    script!("operators"),
    script!("packed_scatter_store"),
    script!("param_override"),
    script!("proto_package"),
    script!("recovered_unrolled_fold"),
    script!("reset_edge_cases"),
    script!("self_determination"),
    script!("shift_bug_test"),
    script!("shift_signedness"),
    script!("signed_divrem"),
    script!("state_cast_semantics"),
    script!("std_binary_codec"),
    script!("std_delay"),
    script!("std_edge_detector"),
    script!("std_fifo"),
    script!("std_gray_codec"),
    script!("std_lfsr"),
    script!("std_mux"),
    script!("std_onehot"),
    script!("std_ram"),
    script!("struct_constructor"),
    script!("synth_dynamic_loop"),
    script!("system_function"),
    script!("test_unimplemented_paths"),
    script!("veryl_context_regressions"),
    script!("veryl_language"),
    script!("veryl_regressions"),
    script!("wide_context_width"),
    script!("wide_data"),
    script!("wide_operators"),
    script!("wide_shift_mem"),
];
