[package]
name = "lydite"
default-run = "lydite"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
lydite-ir.workspace = true
lydite-verify.workspace = true
lydite-syntax.workspace = true

lydite-solver.workspace = true

[lints]
workspace = true
