[package]
name = "hwverify-sir"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
hwverify-ir.workspace = true
serde_json.workspace = true

[dev-dependencies]
hwverify-solver.workspace = true

[[bin]]
name = "hwverify-sir-lift"
path = "src/main.rs"

[lints]
workspace = true
