[package]
name = "celox-frontend-core"
version.workspace = true
publish = ["crates-io"]
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Source-neutral symbolic frontend core for Celox"
edition.workspace = true
rust-version.workspace = true

[dependencies]
celox-design = { workspace = true }
celox-frontend-sdk = { workspace = true }
celox-sir = { workspace = true }
celox-slt = { workspace = true }
fxhash = { workspace = true }
miette = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
