[package]
name = "celox-backend-wasm"
version.workspace = true
publish = ["crates-io"]
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Celox WebAssembly code-generation backend"
edition.workspace = true
rust-version.workspace = true

[dependencies]
celox-design = { workspace = true }
celox-sir = { workspace = true }
celox-state-layout = { workspace = true }
fxhash = { workspace = true }
wasm-encoder = "0.258"

[dev-dependencies]
celox-backend-cranelift = { workspace = true }
num-bigint = { workspace = true }
wasmtime = "48"

[lints]
workspace = true
