[package]
name = "celox-backend-wasm"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Celox WebAssembly code-generation backend"
edition.workspace = true

[dependencies]
celox-design = { path = "../celox-design" }
celox-sir = { path = "../celox-sir" }
celox-state-layout = { path = "../celox-state-layout" }
fxhash = { workspace = true }
wasm-encoder = "0.255"

[dev-dependencies]
celox-backend-cranelift = { path = "../celox-backend-cranelift" }
num-bigint = { workspace = true }
wasmtime = "47"

[lints]
workspace = true
