[package]
name                  = "celox-macros"
version.workspace     = true
publish               = ["crates-io"]
authors.workspace     = true
repository.workspace  = true
license.workspace     = true
description.workspace = true
edition.workspace     = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
fxhash            = { workspace = true }
proc-macro2       = "1.0"
quote             = "1.0"
syn               = { version = "3.0", features = ["full", "extra-traits"] }
veryl-analyzer    = { workspace = true }
veryl-metadata    = { workspace = true }
veryl-parser      = { workspace = true }
num-bigint        = "0.5"

[dev-dependencies]
prettyplease = "0.3.0"
insta        = "1.39.0"

[lints]
workspace = true
