[package]
name                   = "celox-frontend-sv"
version.workspace      = true
authors.workspace      = true
repository.workspace   = true
license.workspace      = true
description            = "SystemVerilog frontend lowering for Celox"
edition.workspace      = true
rust-version.workspace = true

[dependencies]
celox-design         = { path = "../celox-design" }
celox-frontend-veryl = { path = "../celox-frontend-veryl" }
celox-sir            = { path = "../celox-sir" }
celox-slt            = { path = "../celox-slt" }
celox-sv-analyzer    = { path = "../celox-sv-analyzer" }
fxhash               = { workspace = true }
num-bigint           = { workspace = true }
thiserror            = { workspace = true }
veryl-analyzer       = { workspace = true }
veryl-metadata       = { workspace = true }
veryl-parser         = { workspace = true }

[lints]
workspace = true
