[workspace]
exclude = ["conformance/veryl", "conformance/veryl/analyzer-probe", "conformance/veryl-proof"]
members = ["crates/ir", "crates/solver", "crates/verify", "crates/syntax", "crates/cli"]
default-members = ["crates/ir", "crates/solver", "crates/verify", "crates/syntax", "crates/cli"]
resolver = "2"

[workspace.package]
version = "0.13.0"
edition = "2021"

[workspace.dependencies]
serde = "1"
serde_json = "1"
hwverify-ir = { path = "crates/ir" }
hwverify-solver = { path = "crates/solver" }
hwverify-verify = { path = "crates/verify" }
hwverify-syntax = { path = "crates/syntax" }
