[package]
name = "celox-backend-cranelift"
version.workspace = true
publish = ["crates-io"]
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Celox Cranelift code-generation backend"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tracing = { workspace = true }
celox-design = { workspace = true }
celox-sir = { workspace = true }
celox-state-layout = { workspace = true }
fxhash = { workspace = true }
thiserror = { workspace = true }
cranelift = "0.134.0"
cranelift-module = "0.134.0"
cranelift-jit = "0.134.0"
cranelift-frontend = "0.134.0"
cranelift-native = "0.134.0"

[lints]
workspace = true

[dev-dependencies]
num-bigint = { workspace = true }
